stages:
  - name: test
    if: branch != master OR type = pull_request
  - name: deploy
    if: branch = master AND type = pull_request

language: go
os: linux
notifications:
  email: false
jobs:
  include:
    - stage: test
      before_script: ./.travis/prepare.sh
      script: ./.travis/test.sh
    - stage: deploy
      language: shell
      services:
      - docker
      script: ./.travis/deploy.sh
