stages:
  - prepare
  - test
  - name: deploy
    if: branch = master
language: go
sudo: required
services:
  - docker
notifications:
  email: false
jobs:
  include:
    - stage: prepare
    - script: ./.travis/prepare.sh
    - stage: test
    - script: ./.travis/test.sh
    - stage: deploy
    - script: ./.travis/deploy.sh
