stages:
  - name: test
    if: branch != master
  - name: deploy
    if: branch = master AND type = pull_request

notifications:
  email: false
jobs:
  include:
    - stage: test
      language: go
      before_script: ./.travis/prepare.sh
      script: ./.travis/test.sh
    - stage: deploy
      language: minimal
      sudo: required
      services:
      - docker
      script: ./.travis/deploy.sh
