language: go
notifications:
  email: false
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1

script:
  - golangci-lint run
  - go test -v ./...
