language: go
sudo: required
services:
  - docker
notifications:
  email: false
jobs:
  include:
    - stage: test
      before_script: ./.travis/prepare.sh
      script: ./.travis/test.sh
    - stage: deploy
      script: ./.travis/deploy.sh
